# Generated by Django 4.2.1 on 2023-05-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosestPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "closest_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closest_to",
                        to="api.point",
                    ),
                ),
                (
                    "point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.point"
                    ),
                ),
            ],
        ),
    ]
