# Generated by Django 4.2.1 on 2023-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_closestpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closestpoint",
            name="closest_point",
        ),
        migrations.RemoveField(
            model_name="point",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="point",
            name="x",
        ),
        migrations.RemoveField(
            model_name="point",
            name="y",
        ),
        migrations.AddField(
            model_name="closestpoint",
            name="closest_points",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="point",
            name="points",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
